---
title: "Homelab"
subtitle: "Jasper"
logo: "logo.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Networking"
    icon: "fas network-wired"
    items:
      - name: "DNS"
        logo: "assets/icons/technitium-logo.png" 
        subtitle: "DNS and Ad blocker"
        tag: "network"
        tagstyle: "is-primary" 
        url: "http://dns.home"
        target: "_blank"
      - name: "PfSense"
        logo: "assets/icons/pfsense-logo.png"
        subtitle: "Router and DHCP server"
        tag: "network"
        url: "http://pfsense.home"
        target: "_blank"
  - name: "Hypervisor"
    icon: "fas computer"
    items:
      - name: "Proxmox"
        logo: "assets/icons/proxmox-logo.png"
        subtitle: "The one and only"
        tag: "hypervisor"
        url: "https://proxmox.home:8006"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/icons/portainer-logo.svg"
        subtitle: "Hosting all kinds of things"
        tag: "hypervisor"
        type: "Portainer"
        apikey: "ptr_pZTlm5qhFMzEx4zdr56H7fbsWP2oecQ65X4NW5IDom4="
        url: "https://docker-util.home:9443"
        target: "_blank"
  - name: "Util"
    icon: "fas truck-fast"
    items:
      - name: "Stirling PDF"
        logo: "assets/icons/stirling-pdf-logo.jpg"
        subtitle: "For all your PDF needs"
        tag: "util"
        url: "http://docker-util.home:8080"
        target: "_blank"
      - name: "Actual Budget"
        logo: "assets/icons/actual-logo.png"
        subtitle: "Budgetting"
        tag: "util"
        url: "https://docker-util.home:5006"
        target: "_blank"
      - name: "Plant It"
        logo: "assets/icons/plantit-logo.jpg"
        subtitle: "Gardening"
        url: "http://docker-util.home:8081"
        target: "_blank"
  - name: "Automation"
    icon: "fas home"
    items:
      - name: "Home Assistant"
        logo: "assets/icons/home-assistant-logo.png"
        subtitle: "Automation around every corner"
        tag: "automation"
        url: "http://homeassistant.home"
        target: "_blank"



